"use client";

import React, { useState } from 'react';

interface RobotsConfig {
    sitemapUrl: string;
    userAgents: { name: string; rules: { type: 'allow' | 'disallow'; path: string }[] }[];
    crawlDelay?: number;
    additionalSitemaps: string[];
}

const DEFAULT_USER_AGENTS = [
    { name: '*', label: 'All Bots' },
    { name: 'Googlebot', label: 'Google' },
    { name: 'Bingbot', label: 'Bing' },
    { name: 'Slurp', label: 'Yahoo' },
    { name: 'DuckDuckBot', label: 'DuckDuckGo' },
    { name: 'Baiduspider', label: 'Baidu' },
    { name: 'YandexBot', label: 'Yandex' },
    { name: 'facebookexternalhit', label: 'Facebook' },
    { name: 'Twitterbot', label: 'Twitter' },
    { name: 'GPTBot', label: 'ChatGPT' },
    { name: 'Claude-Web', label: 'Claude' },
];

const COMMON_DISALLOW_PATHS = [
    '/admin',
    '/login',
    '/api',
    '/private',
    '/tmp',
    '/cgi-bin',
    '/*.pdf$',
    '/*?*',
];

export const RobotsTool: React.FC = () => {
    const [sitemapUrl, setSitemapUrl] = useState('');
    const [selectedAgents, setSelectedAgents] = useState<string[]>(['*']);
    const [disallowPaths, setDisallowPaths] = useState<string[]>([]);
    const [allowPaths, setAllowPaths] = useState<string[]>([]);
    const [customPath, setCustomPath] = useState('');
    const [crawlDelay, setCrawlDelay] = useState<number | null>(null);
    const [additionalSitemaps, setAdditionalSitemaps] = useState<string[]>([]);
    const [newSitemap, setNewSitemap] = useState('');
    const [copied, setCopied] = useState(false);

    const toggleAgent = (agent: string) => {
        setSelectedAgents(prev =>
            prev.includes(agent)
                ? prev.filter(a => a !== agent)
                : [...prev, agent]
        );
    };

    const toggleDisallowPath = (path: string) => {
        setDisallowPaths(prev =>
            prev.includes(path)
                ? prev.filter(p => p !== path)
                : [...prev, path]
        );
    };

    const addCustomDisallow = () => {
        if (customPath.trim() && !disallowPaths.includes(customPath.trim())) {
            setDisallowPaths(prev => [...prev, customPath.trim()]);
            setCustomPath('');
        }
    };

    const addCustomAllow = () => {
        if (customPath.trim() && !allowPaths.includes(customPath.trim())) {
            setAllowPaths(prev => [...prev, customPath.trim()]);
            setCustomPath('');
        }
    };

    const removeAllowPath = (path: string) => {
        setAllowPaths(prev => prev.filter(p => p !== path));
    };

    const addSitemap = () => {
        if (newSitemap.trim() && !additionalSitemaps.includes(newSitemap.trim())) {
            setAdditionalSitemaps(prev => [...prev, newSitemap.trim()]);
            setNewSitemap('');
        }
    };

    const removeSitemap = (url: string) => {
        setAdditionalSitemaps(prev => prev.filter(s => s !== url));
    };

    const generateRobotsTxt = (): string => {
        const lines: string[] = [];

        // Add comment header
        lines.push('# robots.txt generated by Not Your Average Tools');
        lines.push(`# Generated on: ${new Date().toISOString().split('T')[0]}`);
        lines.push('');

        // Add user agent rules
        selectedAgents.forEach((agent, idx) => {
            lines.push(`User-agent: ${agent}`);

            // Add allow rules first
            allowPaths.forEach(path => {
                lines.push(`Allow: ${path}`);
            });

            // Add disallow rules
            disallowPaths.forEach(path => {
                lines.push(`Disallow: ${path}`);
            });

            // Add crawl delay if set
            if (crawlDelay && crawlDelay > 0) {
                lines.push(`Crawl-delay: ${crawlDelay}`);
            }

            if (idx < selectedAgents.length - 1) {
                lines.push('');
            }
        });

        // Add sitemaps
        if (sitemapUrl.trim() || additionalSitemaps.length > 0) {
            lines.push('');
            if (sitemapUrl.trim()) {
                lines.push(`Sitemap: ${sitemapUrl.trim()}`);
            }
            additionalSitemaps.forEach(sitemap => {
                lines.push(`Sitemap: ${sitemap}`);
            });
        }

        return lines.join('\n');
    };

    const robotsTxt = generateRobotsTxt();

    const copyToClipboard = () => {
        navigator.clipboard.writeText(robotsTxt);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const downloadFile = () => {
        const blob = new Blob([robotsTxt], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'robots.txt';
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 max-w-6xl mx-auto">
            {/* Configuration Panel */}
            <div className="space-y-6">
                {/* Sitemap URL */}
                <div className="bg-white dark:bg-surface-dark rounded-2xl border border-gray-200 dark:border-white/10 p-6">
                    <h3 className="text-sm font-bold text-text-main dark:text-white mb-4 flex items-center gap-2">
                        <span className="material-symbols-outlined text-primary text-lg">map</span>
                        Sitemap URL
                    </h3>
                    <input
                        type="url"
                        value={sitemapUrl}
                        onChange={(e) => setSitemapUrl(e.target.value)}
                        placeholder="https://example.com/sitemap.xml"
                        className="w-full px-4 py-3 bg-gray-50 dark:bg-white/5 border border-gray-200 dark:border-white/10 rounded-xl text-text-main dark:text-white placeholder:text-gray-400 focus:outline-none focus:ring-2 focus:ring-primary/50"
                    />

                    {/* Additional Sitemaps */}
                    <div className="mt-4">
                        <div className="flex gap-2">
                            <input
                                type="url"
                                value={newSitemap}
                                onChange={(e) => setNewSitemap(e.target.value)}
                                placeholder="Add another sitemap..."
                                className="flex-1 px-3 py-2 text-sm bg-gray-50 dark:bg-white/5 border border-gray-200 dark:border-white/10 rounded-lg text-text-main dark:text-white placeholder:text-gray-400 focus:outline-none focus:ring-2 focus:ring-primary/50"
                                onKeyDown={(e) => e.key === 'Enter' && addSitemap()}
                            />
                            <button
                                onClick={addSitemap}
                                className="px-3 py-2 bg-primary/10 text-primary rounded-lg hover:bg-primary/20 transition-colors text-sm font-medium"
                            >
                                Add
                            </button>
                        </div>
                        {additionalSitemaps.length > 0 && (
                            <div className="flex flex-wrap gap-2 mt-3">
                                {additionalSitemaps.map((url, idx) => (
                                    <span key={idx} className="inline-flex items-center gap-1.5 px-2 py-1 bg-blue-50 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400 rounded-lg text-xs">
                                        <span className="truncate max-w-[200px]">{url}</span>
                                        <button onClick={() => removeSitemap(url)} className="hover:text-red-500">
                                            <span className="material-symbols-outlined text-sm">close</span>
                                        </button>
                                    </span>
                                ))}
                            </div>
                        )}
                    </div>
                </div>

                {/* User Agents */}
                <div className="bg-white dark:bg-surface-dark rounded-2xl border border-gray-200 dark:border-white/10 p-6">
                    <h3 className="text-sm font-bold text-text-main dark:text-white mb-4 flex items-center gap-2">
                        <span className="material-symbols-outlined text-primary text-lg">smart_toy</span>
                        User Agents
                    </h3>
                    <div className="flex flex-wrap gap-2">
                        {DEFAULT_USER_AGENTS.map((agent) => (
                            <button
                                key={agent.name}
                                onClick={() => toggleAgent(agent.name)}
                                className={`px-3 py-1.5 rounded-lg text-sm font-medium transition-all ${selectedAgents.includes(agent.name)
                                        ? 'bg-primary text-white'
                                        : 'bg-gray-100 dark:bg-white/5 text-text-sub dark:text-gray-400 hover:bg-gray-200 dark:hover:bg-white/10'
                                    }`}
                            >
                                {agent.label}
                            </button>
                        ))}
                    </div>
                </div>

                {/* Disallow Paths */}
                <div className="bg-white dark:bg-surface-dark rounded-2xl border border-gray-200 dark:border-white/10 p-6">
                    <h3 className="text-sm font-bold text-text-main dark:text-white mb-4 flex items-center gap-2">
                        <span className="material-symbols-outlined text-red-500 text-lg">block</span>
                        Disallow Paths
                    </h3>
                    <div className="flex flex-wrap gap-2 mb-4">
                        {COMMON_DISALLOW_PATHS.map((path) => (
                            <button
                                key={path}
                                onClick={() => toggleDisallowPath(path)}
                                className={`px-3 py-1.5 rounded-lg text-sm font-mono transition-all ${disallowPaths.includes(path)
                                        ? 'bg-red-500 text-white'
                                        : 'bg-gray-100 dark:bg-white/5 text-text-sub dark:text-gray-400 hover:bg-red-50 dark:hover:bg-red-900/20 hover:text-red-600 dark:hover:text-red-400'
                                    }`}
                            >
                                {path}
                            </button>
                        ))}
                    </div>
                    <div className="flex gap-2">
                        <input
                            type="text"
                            value={customPath}
                            onChange={(e) => setCustomPath(e.target.value)}
                            placeholder="/custom-path"
                            className="flex-1 px-3 py-2 text-sm font-mono bg-gray-50 dark:bg-white/5 border border-gray-200 dark:border-white/10 rounded-lg text-text-main dark:text-white placeholder:text-gray-400 focus:outline-none focus:ring-2 focus:ring-primary/50"
                            onKeyDown={(e) => e.key === 'Enter' && addCustomDisallow()}
                        />
                        <button
                            onClick={addCustomDisallow}
                            className="px-3 py-2 bg-red-500/10 text-red-500 rounded-lg hover:bg-red-500/20 transition-colors text-sm font-medium"
                        >
                            Disallow
                        </button>
                        <button
                            onClick={addCustomAllow}
                            className="px-3 py-2 bg-green-500/10 text-green-500 rounded-lg hover:bg-green-500/20 transition-colors text-sm font-medium"
                        >
                            Allow
                        </button>
                    </div>

                    {/* Allow paths list */}
                    {allowPaths.length > 0 && (
                        <div className="mt-4">
                            <p className="text-xs font-medium text-green-600 dark:text-green-400 mb-2">Allowed paths:</p>
                            <div className="flex flex-wrap gap-2">
                                {allowPaths.map((path, idx) => (
                                    <span key={idx} className="inline-flex items-center gap-1.5 px-2 py-1 bg-green-50 dark:bg-green-900/20 text-green-600 dark:text-green-400 rounded-lg text-xs font-mono">
                                        {path}
                                        <button onClick={() => removeAllowPath(path)} className="hover:text-red-500">
                                            <span className="material-symbols-outlined text-sm">close</span>
                                        </button>
                                    </span>
                                ))}
                            </div>
                        </div>
                    )}
                </div>

                {/* Crawl Delay */}
                <div className="bg-white dark:bg-surface-dark rounded-2xl border border-gray-200 dark:border-white/10 p-6">
                    <h3 className="text-sm font-bold text-text-main dark:text-white mb-4 flex items-center gap-2">
                        <span className="material-symbols-outlined text-primary text-lg">timer</span>
                        Crawl Delay (seconds)
                    </h3>
                    <div className="flex items-center gap-4">
                        <input
                            type="range"
                            min="0"
                            max="60"
                            value={crawlDelay || 0}
                            onChange={(e) => setCrawlDelay(parseInt(e.target.value) || null)}
                            className="flex-1 accent-primary"
                        />
                        <span className="w-12 text-center font-mono text-text-main dark:text-white">
                            {crawlDelay || 0}s
                        </span>
                    </div>
                    <p className="text-xs text-gray-500 mt-2">
                        Set to 0 to not include crawl-delay directive
                    </p>
                </div>
            </div>

            {/* Preview Panel */}
            <div className="lg:sticky lg:top-6 h-fit">
                <div className="bg-white dark:bg-surface-dark rounded-2xl border border-gray-200 dark:border-white/10 overflow-hidden">
                    <div className="px-4 py-3 bg-gray-50 dark:bg-white/5 border-b border-gray-200 dark:border-white/10 flex items-center justify-between">
                        <div className="flex items-center gap-2">
                            <span className="material-symbols-outlined text-primary">description</span>
                            <span className="font-bold text-sm text-text-main dark:text-white">robots.txt</span>
                        </div>
                        <div className="flex items-center gap-2">
                            <button
                                onClick={copyToClipboard}
                                className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-text-sub dark:text-gray-400 hover:text-primary border border-gray-200 dark:border-white/10 rounded-lg hover:bg-gray-50 dark:hover:bg-white/5 transition-all"
                            >
                                <span className="material-symbols-outlined text-sm">
                                    {copied ? 'check' : 'content_copy'}
                                </span>
                                {copied ? 'Copied!' : 'Copy'}
                            </button>
                            <button
                                onClick={downloadFile}
                                className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-white bg-primary rounded-lg hover:bg-primary/90 transition-all"
                            >
                                <span className="material-symbols-outlined text-sm">download</span>
                                Download
                            </button>
                        </div>
                    </div>
                    <pre className="p-4 text-sm font-mono text-text-main dark:text-green-400 bg-gray-50 dark:bg-[#0d1117] overflow-x-auto min-h-[400px] whitespace-pre-wrap">
                        {robotsTxt}
                    </pre>
                </div>

                {/* Quick Info */}
                <div className="mt-4 bg-blue-50 dark:bg-blue-900/20 rounded-xl p-4 border border-blue-100 dark:border-blue-800">
                    <h4 className="font-bold text-sm text-blue-700 dark:text-blue-300 mb-2 flex items-center gap-2">
                        <span className="material-symbols-outlined text-lg">info</span>
                        Quick Tips
                    </h4>
                    <ul className="text-xs text-blue-600 dark:text-blue-400 space-y-1">
                        <li>• Place robots.txt in your site's root directory</li>
                        <li>• Use "*" to apply rules to all crawlers</li>
                        <li>• Test with Google Search Console before deploying</li>
                        <li>• Block AI crawlers (GPTBot, Claude-Web) if needed</li>
                    </ul>
                </div>
            </div>
        </div>
    );
};
